apiVersion: v3
name: churchtools-song-importer
description: A service that uploads songs to ChurchTools

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
<<<<<<< Updated upstream
version: 0.0.7
=======
version: 1.2.2
>>>>>>> Stashed changes
=======
version: 1.2
>>>>>>> 06dabd45e5edc5c7e30fb41fb2be9478ca7c659f

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
<<<<<<< HEAD
<<<<<<< Updated upstream
appVersion: "1.4"
=======
appVersion: 1.6
>>>>>>> Stashed changes
=======
appVersion: "1.5"
>>>>>>> 06dabd45e5edc5c7e30fb41fb2be9478ca7c659f
