namespace: churchtools

service:

  name: churchtools-song-importer
  
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: "1"
  failedJobsHistoryLimit: "3"

  image:
    repository: repo
    name: infrastructure/churchtools-song-importer
    version: "1.3"
    pullSecret: dockerregistry

  environment:
    # Delete mode
    CMD_DELETE: "False"
    # Add mode
    CMD_ADD: "True"
    # Cleanup songs without an internal ID after running (be careful!)
    CMD_CLEANUP: "False"
    # Type of songs to handle (gb or sb or both comman separated)
    TYPE: "gb"
    # Source of files (can be nc for nextcloud or local)
    SOURCE: "nc"
    # Number of single song to add / sync
    # NUMBER: ""
    # Skip update of existing songs and only crete new ones
    SKIP_UPDATE: "False"
    # Path to the TXT file with the Gesangbuch metadata (locally)
    GB_TXT_FILE: "files/gesangbuch.txt"
    # Path to the Gesangbuch slides files
    GB_FILE_PATH: "gb_songs"
    # Path to the Songbeamer song files
    SB_FILE_PATH: "sb_songs"
    # URL of the nextcloud instance
    NEXTCLOUD_URL: "https://my.cloud.de"
    # User for the nextcloud instance
    NEXTCLOUD_USER: "username"
    # Password for the nextcloud instance
    NEXTCLOUD_PASS: "my-token-here"
    # URL of the ChurchTools instance
    CT_URL: "https://myinstance.church.tools/api" 
    # API token for the ChurchTools instance
    CT_API_TOKEN: "ct-api-token"
    # ChurchTools category for Gesangbuch songs
    CT_SONG_CATEGORY_GB: "EmK Gesangbuch"
    # ChurchTools category for Songbeamer songs
    CT_SONG_CATEGORY_SB: "Lobpreislieder"
    # ChurchTools arrangement name to use
    CT_SONG_ARRANGEMENT_NAME: "My arrangement"
    # Campus name of the congregation to filter for the correct category
    CT_CAMPUS_NAME: "My congregation"
    # Loglevel
    LOGLEVEL: "INFO"

  # Secret to use for environment variables (key = env var name, value = var value)

  volumes:
    - name: churchtools-song-importer-gesangbuch
      mountPath: /usr/source/app/files
      configMap: churchtools-song-importer-gesangbuch